//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Haberler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Haberler()
        {
            this.HaberYorumlar = new HashSet<HaberYorumlar>();
        }
    
        public int haberId { get; set; }
        public string haberKategori { get; set; }
        public string haberBaslik { get; set; }
        public string haberIcerik { get; set; }
        public string haberResim { get; set; }
        public string haberVideo { get; set; }
        public System.DateTime haberTarih { get; set; }
        public int haberOkunma { get; set; }
        public int haberYazarId { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual uyeler uyeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HaberYorumlar> HaberYorumlar { get; set; }
    }
}
