//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HaberYorumlar
    {
        public int yorumId { get; set; }
        public string yorumIcerik { get; set; }
        public System.DateTime yorumTarih { get; set; }
        public int yorumHaberId { get; set; }
    
        public virtual Haberler Haberler { get; set; }
    }
}
