//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uyeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uyeler()
        {
            this.Haberler = new HashSet<Haberler>();
        }
    
        public int uyeId { get; set; }
        public string adsoyad { get; set; }
        public string mail { get; set; }
        public string parola { get; set; }
        public string telefon { get; set; }
        public string haberAlan { get; set; }
        public string konum { get; set; }
        public string rol { get; set; }
        public System.DateTime kayitTarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Haberler> Haberler { get; set; }
    }
}
